# # Buat folder public
mkdir public

# Buat folder netlify/functions
mkdir -p netlify/functions

# Pindahkan file statis
mv index.html public/
mv styles.css public/
mv script.js public/

# Pindahkan fungsi serverless
mv send-dana-bansos.js netlify/functions/
